clear;
clc;
x=-10:1:10;
p=[1 -5 -30 110 29 -105];
p_strich=polyder(p);
p_stamm=polyint(p);
y=polyval(p,x);
y_strich=polyval(p_strich,x);
y_stamm=polyval(p_stamm,x);
x0=roots(p);
hold on;
figure(1);
plot(x,y,'r');
plot(x,y_strich,'g');
plot(x,y_stamm,'b');
legend('f','f-strich','F');
xlim([min(x0) max(x0)]);
grid;
hold off;
x=-3:1:3;
y=-3:1:3;
[x,y] = meshgrid(-3:0.1:3);
x_alternativ=-x;
y_alternativ=-y;
z=x.*exp((x_alternativ.^2)+(y_alternativ.^2));
figure(2);
mesh(x,y,z);
view(20,15);